### PR TITLE
PFM-987 :: Works UI Deployment configured

### PR DESCRIPTION
**Pull request by jagankumar-egov**

### CODE REVIEW

**Review by rushang7-eGov — COMMENTED** [review]
As we are developing this new project `works-ui` as part of the DIGIT-Works, I suggest moving it to the new folder. 
Make a new folder named `digit-works` in the charts directory. Within that follow the same directory structure i.e. create a works-ui helm chart inside the frontend folder. 
So the directory structure will `.../charts/digit-works/frontend/works-ui`

**Comment by jagankumar-egov** [comment]
Updated

**Review by rushang7-eGov — COMMENTED** [review]
Follow the current naming pattern. Rename the dir. `Digit-Works` to `digit-works`.

**Comment by jagankumar-egov** [comment]
closing this as new pr was created 
https://github.com/egovernments/DIGIT-DevOps/pull/956

**Pull request closed without merging**
