### PR TITLE
Update elasticsearch-master-infra-v1-values.yaml

### PR DESCRIPTION
**Pull request by ashutoshpatnaikegov**

### CODE REVIEW

**Comment by ashutoshpatnaikegov** [comment]
Need to increase the space in Elasticsearch

**Review by nikesh-eGov — COMMENTED** [review]
Why do you need that much resource. If u want to change the resources for any env, change it through respective env.yaml

**Comment by ashutoshpatnaikegov** [comment]
Ok Nikesh

**Comment by nikesh-eGov** [comment]
raise fresh PR. I am closing this one.

**Pull request closed without merging**
